name: BuildTest

on:
  push:
  pull_request:

    
jobs:
  docker-build-test-ubuntu:
    runs-on: ubuntu-latest
    name: Build Test SMARDDA-DAGMC container
    env: 
      PRCOMMITSHA : ${{ github.event.pull_request.head.sha }}
    steps:
    # Check out repo to get Dockerfile
    - name: Checkout
      uses: actions/checkout@v2
    # Build container and run tests from limited_build Dockerfile 
    - name: PrintGithubContext
      run: echo $PRCOMMITSHA
    - name: DockerBuildTestPull 
      if: ${{ github.event.pull_request.head.sha != '' }} 
      run: docker build -t ci-dagmc-ubuntu --build-arg build_git_sha=$PRCOMMITSHA docker/limited_build/
    - name: DockerBuildTestPush
      if: ${{ github.event.pull_request.head.sha == '' }}
      run: docker build -t ci-dagmc-ubuntu --build-arg build_git_sha=$GITHUB_SHA docker/limited_build/
