name: SMARDDA-DAGMC Image Push

on:
  schedule:
  - cron: "0 0 * * 5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/weekly_build/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/smardda-dagmc/v1
