name: BuildTest

on:
  push:
  pull_request:

    
jobs:
  docker-build-test-ubuntu:
    runs-on: ubuntu-latest
    container: 
      image: waqar1711/smardda-dagmc:v1
      credentials: 
        username: ${{ secrets.DOCKERHUB_USERNAME }} 
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    name: BuildTestUbuntuContainer 
    env: 
      PRCOMMITSHA : ${{ github.event.pull_request.head.sha }}
    steps:
    # Check out repo to get Dockerfile
    - name: Checkout
      uses: actions/checkout@v2
    # Build Ubuntu container containing DAGMC 
    - name: PrintGithubContext
      run: echo $PRCOMMITSHA
    - name: DockerBuildTestPull 
      if: ${{ github.event.pull_request.head.sha != '' }} 
      run: docker build -t ci-dagmc-ubuntu --build-arg build_git_sha=$PRCOMMITSHA docker/limited_build/
    - name: DockerBuildTestPush
      if: ${{ github.event.pull_request.head.sha == '' }}
      run: docker build -t ci-dagmc-ubuntu --build-arg build_git_sha=$GITHUB_SHA docker/limited_build
